"""add facebook_id column

Revision ID: 58896536d1dc
Revises: 
Create Date: 2025-04-23 19:04:00.633959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58896536d1dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_connected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('facebook_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.drop_index('ix_users_instagram_id', table_name='users')
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.drop_column('users', 'instagram_id')
    op.drop_column('users', 'instagram_token')
    op.drop_column('users', 'instagram_connected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_connected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('instagram_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('instagram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.create_index('ix_users_instagram_id', 'users', ['instagram_id'], unique=True)
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'facebook_token')
    op.drop_column('users', 'facebook_connected')
    # ### end Alembic commands ###
