"""add_anonymous_user_id_to_runpod_request

Revision ID: bc0952c8eed1
Revises: 58896536d1dc
Create Date: 2025-04-23 23:31:51.639732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0952c8eed1'
down_revision: Union[str, None] = '58896536d1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runpod_requests', sa.Column('anonymous_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_runpod_requests_anonymous_user_id'), 'runpod_requests', ['anonymous_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runpod_requests_anonymous_user_id'), table_name='runpod_requests')
    op.drop_column('runpod_requests', 'anonymous_user_id')
    # ### end Alembic commands ###
